version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_PASSWORD: ncpass
    volumes:
      - /HDD/nextcloud/db:/var/lib/mysql

  app:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "84:80"
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: ncpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: ncuser
      MYSQL_HOST: db
    volumes:
      - /HDD/nextcloud/html:/var/www/html
