version: "3.8"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: always
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /SSD/plex/config:/config
      - /HDD/media/movies:/movies
      - /HDD/media/tv:/tv
      - /HDD/media/music:/music